version = 0.1
[default.deploy.parameters]
stack_name = "TwilioS3VoicemailUploaderStack"
resolve_s3 = true
s3_prefix = "TwilioS3VoicemailUploaderStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"twilio-voicemail-storage\""
image_repositories = []
